

const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const REFETCH_GROUP_DETAIL = "REFETCH_GROUP_DETAIL";
const ADDED_IN_GROUP = "ADDED_IN_GROUP";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

const NEW_MESSAGE = "NEW_MESSAGE";
const USER_ONLINE = "USER_ONLINE";
const USER_OFFLINE = "USER_OFFLINE";
const TYPING_MESSAGE = "TYPING_MESSAGE";
const TYPING_SOPPED_MESSAGE = "TYPING_SOPPED_MESSAGE";

export  {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  REFETCH_GROUP_DETAIL,
  ADDED_IN_GROUP,
  TYPING_MESSAGE,
  TYPING_SOPPED_MESSAGE,
  USER_OFFLINE,
  USER_ONLINE
}